(function() {
  if (window.__githubZhLoaded) return;
  window.__githubZhLoaded = true;

  var T = {
    "Pull requests": "拉取请求",
    "Issues": "议题",
    "Codespaces": "代码空间",
    "Marketplace": "市场",
    "Explore": "探索",
    "Notifications": "通知",
    "Sign in": "登录",
    "Sign up": "注册",
    "Sign out": "退出登录",
    "Settings": "设置",
    "Profile": "个人资料",
    "Your profile": "你的个人资料",
    "Your repositories": "你的仓库",
    "Your codespaces": "你的代码空间",
    "Your organizations": "你的组织",
    "Your enterprises": "你的企业",
    "Your projects": "你的项目",
    "Your stars": "你的星标",
    "Your gists": "你的代码片段",
    "Sponsors": "赞助",
    "New": "新建",
    "New repository": "新建仓库",
    "New codespace": "新建代码空间",
    "New gist": "新建代码片段",
    "New organization": "新建组织",
    "New project": "新建项目",
    "Import repository": "导入仓库",
    "New issue": "新建议题",
    "Code": "代码",
    "Actions": "操作",
    "Projects": "项目",
    "Wiki": "维基",
    "Security": "安全",
    "Insights": "洞察",
    "Releases": "发布",
    "Packages": "包",
    "Deployments": "部署",
    "Discussions": "讨论",
    "About": "关于",
    "Contributors": "贡献者",
    "Languages": "语言",
    "Used by": "被使用",
    "Tags": "标签",
    "Forks": "复刻",
    "Stars": "星标",
    "Watching": "关注中",
    "Watch": "关注",
    "Star": "星标",
    "Fork": "复刻",
    "Unstar": "取消星标",
    "Unwatch": "取消关注",
    "Edit": "编辑",
    "Delete": "删除",
    "Create": "创建",
    "Save": "保存",
    "Cancel": "取消",
    "Close": "关闭",
    "Reopen": "重新打开",
    "Merge": "合并",
    "Submit": "提交",
    "Update": "更新",
    "Add": "添加",
    "Remove": "移除",
    "Copy": "复制",
    "Download": "下载",
    "Upload": "上传",
    "Search": "搜索",
    "Filter": "筛选",
    "Sort": "排序",
    "Clear": "清除",
    "Refresh": "刷新",
    "More": "更多",
    "Less": "收起",
    "Show": "显示",
    "Hide": "隐藏",
    "Expand": "展开",
    "Collapse": "折叠",
    "Open": "打开",
    "Closed": "已关闭",
    "Merged": "已合并",
    "Draft": "草稿",
    "Reopened": "已重新打开",
    "Open issues": "打开的议题",
    "Closed issues": "已关闭的议题",
    "Open pull requests": "打开的拉取请求",
    "Closed pull requests": "已关闭的拉取请求",
    "Merged pull requests": "已合并的拉取请求",
    "All": "全部",
    "No results": "无结果",
    "No matching results": "无匹配结果",
    "No issues found": "未找到议题",
    "No pull requests found": "未找到拉取请求",
    "Overview": "概览",
    "Repositories": "仓库",
    "Repository": "仓库",
    "Followers": "关注者",
    "Following": "关注中",
    "Sponsoring": "赞助中",
    "Sponsored": "已赞助",
    "Contribution activity": "贡献活动",
    "Contributions": "贡献",
    "Pinned": "已置顶",
    "Popular repositories": "热门仓库",
    "Pinned repositories": "已置顶仓库",
    "Contribute": "贡献",
    "Sponsor this project": "赞助此项目",
    "Add file": "添加文件",
    "Go to file": "转到文件",
    "Create new file": "创建新文件",
    "Upload files": "上传文件",
    "Clone": "克隆",
    "Download ZIP": "下载 ZIP",
    "Open with GitHub Desktop": "用 GitHub Desktop 打开",
    "Open with Codespaces": "用代码空间打开",
    "Use a template": "使用模板",
    "Branch": "分支",
    "Branches": "分支",
    "Default branch": "默认分支",
    "Switch branches/tags": "切换分支/标签",
    "Find a branch": "查找分支",
    "View all branches": "查看所有分支",
    "View all tags": "查看所有标签",
    "Recent commits": "最近提交",
    "Commits": "提交",
    "Commit": "提交",
    "committed": "已提交",
    "Authored by": "作者",
    "Committed by": "提交者",
    "Last commit message": "最后提交信息",
    "History": "历史",
    "Blame": "追溯",
    "Raw": "原始",
    "Edit this file": "编辑此文件",
    "Delete this file": "删除此文件",
    "Rename this file": "重命名此文件",
    "View raw": "查看原始内容",
    "Copy raw contents": "复制原始内容",
    "Download raw file": "下载原始文件",
    "Permalink": "永久链接",
    "Preview": "预览",
    "Write": "编写",
    "Markdown": "Markdown",
    "Attach files": "附加文件",
    "Leave a comment": "留下评论",
    "Comment": "评论",
    "Comments": "评论",
    "Reactions": "反应",
    "Labels": "标签",
    "Label": "标签",
    "Milestones": "里程碑",
    "Milestone": "里程碑",
    "Assignees": "负责人",
    "Assignee": "负责人",
    "Reviewers": "审核者",
    "Reviewer": "审核者",
    "Linked pull requests": "关联的拉取请求",
    "Linked issues": "关联的议题",
    "Development": "开发",
    "Successfully linked": "关联成功",
    "Reference in new issue": "在新议题中引用",
    "Copy link": "复制链接",
    "Quote reply": "引用回复",
    "Report content": "举报内容",
    "Edit comment": "编辑评论",
    "Delete comment": "删除评论",
    "Hide comment": "隐藏评论",
    "Show comment": "显示评论",
    "Subscribe": "订阅",
    "Unsubscribe": "取消订阅",
    "Mute": "静音",
    "Unmute": "取消静音",
    "Pin": "置顶",
    "Unpin": "取消置顶",
    "Lock": "锁定",
    "Unlock": "解锁",
    "Transfer": "转移",
    "Convert to discussion": "转为讨论",
    "Create a pull request": "创建拉取请求",
    "Compare changes": "比较更改",
    "Comparing changes": "比较更改",
    "base": "基础",
    "compare": "比较",
    "Able to merge": "可以合并",
    "Merge pull request": "合并拉取请求",
    "Close pull request": "关闭拉取请求",
    "Reopen pull request": "重新打开拉取请求",
    "Squash and merge": "压缩并合并",
    "Rebase and merge": "变基并合并",
    "Create a merge commit": "创建合并提交",
    "Pull request successfully merged": "拉取请求合并成功",
    "Pull request successfully closed": "拉取请求关闭成功",
    "File changed": "文件已更改",
    "Files changed": "文件已更改",
    "Changes": "更改",
    "Checks": "检查",
    "Conversation": "对话",
    "No files changed": "无文件更改",
    "Show all changes": "显示所有更改",
    "Load diff": "加载差异",
    "Large diffs are not rendered by default": "大型差异默认不渲染",
    "Load more": "加载更多",
    "View file": "查看文件",
    "View entire file": "查看完整文件",
    "Expand all": "全部展开",
    "Collapse all": "全部折叠",
    "Viewed": "已查看",
    "Changes from": "更改来自",
    "No changes": "无更改",
    "Binary file": "二进制文件",
    "Not rendered": "未渲染",
    "Image": "图片",
    "Release": "发布",
    "Latest release": "最新发布",
    "Pre-release": "预发布",
    "Assets": "资源",
    "Source code": "源代码",
    "Source code (zip)": "源代码 (zip)",
    "Source code (tar.gz)": "源代码 (tar.gz)",
    "Published by": "发布者",
    "Published on": "发布于",
    "Released on": "发布于",
    "Tagged on": "标记于",
    "New release": "新发布",
    "Draft a new release": "起草新发布",
    "Choose a tag": "选择标签",
    "Find a tag": "查找标签",
    "Release title": "发布标题",
    "Describe this release": "描述此发布",
    "Previous releases": "以前的发布",
    "Not watching": "未关注",
    "Ignoring": "忽略中",
    "All notifications": "所有通知",
    "Unread": "未读",
    "Read": "已读",
    "Mark as read": "标记为已读",
    "Mark all as read": "全部标记为已读",
    "Mark as done": "标记为完成",
    "No new notifications": "无新通知",
    "You're all caught up!": "你已全部查看！",
    "Manage notification settings": "管理通知设置",
    "Search notifications": "搜索通知",
    "Customize": "自定义",
    "By repository": "按仓库",
    "By organization": "按组织",
    "Bookmarks": "书签",
    "New discussion": "新讨论",
    "Categories": "分类",
    "Announcements": "公告",
    "Ideas": "想法",
    "Q&A": "问答",
    "Show more": "显示更多",
    "Upvote": "赞同",
    "Downvote": "反对",
    "Reply": "回复",
    "Mark as answer": "标记为答案",
    "Unmark as answer": "取消标记为答案",
    "Edit discussion": "编辑讨论",
    "Delete discussion": "删除讨论",
    "Transfer discussion": "转移讨论",
    "Pin discussion": "置顶讨论",
    "Unpin discussion": "取消置顶讨论",
    "Lock discussion": "锁定讨论",
    "Unlock discussion": "解锁讨论",
    "Create discussion": "创建讨论",
    "Search or jump to...": "搜索或跳转到...",
    "Type to search": "输入以搜索",
    "Search all of GitHub": "搜索整个 GitHub",
    "Search GitHub": "搜索 GitHub",
    "Jump to": "跳转到",
    "Team": "团队",
    "Organization": "组织",
    "Enterprise": "企业",
    "Dashboard": "仪表盘",
    "Home": "首页",
    "Your work": "你的工作",
    "Organizations": "组织",
    "Starred": "已星标",
    "Trending": "趋势",
    "Trending repositories": "趋势仓库",
    "Trending developers": "趋势开发者",
    "Collections": "集合",
    "Topics": "主题",
    "Events": "活动",
    "GitHub Sponsors": "GitHub 赞助",
    "Sponsor an open source developer": "赞助开源开发者",
    "Become a sponsor": "成为赞助者",
    "Create your profile": "创建你的个人资料",
    "Edit profile": "编辑个人资料",
    "Set status": "设置状态",
    "What's happening?": "有什么新鲜事？",
    "Busy": "忙碌",
    "On vacation": "休假中",
    "Working from home": "在家办公",
    "Meeting": "会议中",
    "Commuting": "通勤中",
    "Out sick": "病假中",
    "Vacationing": "度假中",
    "Focusing": "专注中",
    "Parenting": "育儿中",
    "Unwell": "不适中",
    "Clear status": "清除状态",
    "Change your status": "更改你的状态",
    "Emoji": "表情",
    "Limit to organization": "仅限组织",
    "Never": "从不",
    "30 minutes": "30 分钟",
    "1 hour": "1 小时",
    "4 hours": "4 小时",
    "Today": "今天",
    "This week": "本周",
    "Account": "账户",
    "Appearance": "外观",
    "Accessibility": "辅助功能",
    "Billing": "账单",
    "Emails": "电子邮件",
    "Security log": "安全日志",
    "SSH and GPG keys": "SSH 和 GPG 密钥",
    "Sessions": "会话",
    "Applications": "应用程序",
    "Developer settings": "开发者设置",
    "Enterprises": "企业",
    "Moderation": "审核",
    "Blocked users": "已屏蔽用户",
    "Interaction limits": "交互限制",
    "Code review limits": "代码审核限制",
    "Saved replies": "保存的回复",
    "Developer program": "开发者计划",
    "Sponsorship log": "赞助日志",
    "Installations": "安装",
    "Personal access tokens": "个人访问令牌",
    "OAuth Apps": "OAuth 应用",
    "GitHub Apps": "GitHub 应用",
    "Connected accounts": "已连接账户",
    "Webhooks": "Webhooks",
    "Deploy keys": "部署密钥",
    "General": "常规",
    "Secrets": "密钥",
    "Variables": "变量",
    "Runners": "运行器",
    "Environments": "环境",
    "Workflow permissions": "工作流权限",
    "Pages": "页面",
    "Collaborators": "协作者",
    "Code security and analysis": "代码安全与分析",
    "Dependabot": "Dependabot",
    "CodeQL": "CodeQL",
    "Integrations": "集成",
    "Moderators": "版主",
    "Member": "成员",
    "Members": "成员",
    "People": "人员",
    "Teams": "团队",
    "Invitations": "邀请",
    "Audit log": "审计日志",
    "Archive": "归档",
    "Danger Zone": "危险区域",
    "Delete this repository": "删除此仓库",
    "Transfer ownership": "转让所有权",
    "Archive this repository": "归档此仓库",
    "Change repository visibility": "更改仓库可见性",
    "Public": "公开",
    "Private": "私有",
    "Internal": "内部",
    "Template": "模板",
    "Use this template": "使用此模板",
    "Create a new repository": "创建新仓库",
    "Open in new window": "在新窗口中打开",
    "Share": "分享",
    "Report abuse": "举报滥用",
    "Go to line": "转到行",
    "Copy path": "复制路径",
    "Copy permalink": "复制永久链接",
    "Copy raw URL": "复制原始 URL",
    "Open with": "打开方式",
    "Normal view": "普通视图",
    "Split view": "分屏视图",
    "Unified view": "统一视图",
    "Diff view": "差异视图",
    "Hide whitespace changes": "隐藏空白更改",
    "Show whitespace changes": "显示空白更改",
    "Ignore whitespace": "忽略空白",
    "Show less": "显示更少",
    "View all": "查看全部",
    "View more": "查看更多",
    "Continue": "继续",
    "Back": "返回",
    "Next": "下一步",
    "Previous": "上一步",
    "Finish": "完成",
    "Done": "完成",
    "OK": "确定",
    "Yes": "是",
    "No": "否",
    "Apply": "应用",
    "Reset": "重置",
    "Restore": "恢复",
    "Undo": "撤销",
    "Redo": "重做",
    "Confirm": "确认",
    "Confirm delete": "确认删除",
    "Are you sure?": "你确定吗？",
    "This action cannot be undone": "此操作无法撤销",
    "Learn more": "了解更多",
    "Read more": "阅读更多",
    "See more": "查看更多",
    "Documentation": "文档",
    "Help": "帮助",
    "Support": "支持",
    "Feedback": "反馈",
    "Contact": "联系",
    "Terms": "条款",
    "Privacy": "隐私",
    "Status": "状态",
    "Blog": "博客",
    "Docs": "文档",
    "API": "API",
    "Training": "培训",
    "Community": "社区",
    "Forum": "论坛",
    "Changelog": "更新日志",
    "Feature preview": "功能预览",
    "GitHub Docs": "GitHub 文档",
    "GitHub Community": "GitHub 社区",
    "GitHub Skills": "GitHub 技能",
    "GitHub Explore": "GitHub 探索",
    "GitHub Marketplace": "GitHub 市场",
    "GitHub for mobile": "GitHub 移动版",
    "GitHub CLI": "GitHub CLI",
    "GitHub Desktop": "GitHub Desktop",
    "GitHub Actions": "GitHub Actions",
    "GitHub Packages": "GitHub Packages",
    "GitHub Security": "GitHub 安全",
    "GitHub Copilot": "GitHub Copilot",
    "GitHub Codespaces": "GitHub 代码空间",
    "GitHub Enterprise": "GitHub 企业版",
    "GitHub Education": "GitHub 教育",
    "Free": "免费",
    "Pro": "专业版",
    "Team": "团队版",
    "Upgrade": "升级",
    "Downgrade": "降级",
    "Renew": "续订",
    "Change plan": "更改计划",
    "Compare plans": "比较计划",
    "Features": "功能",
    "Pricing": "定价",
    "Contact Sales": "联系销售",
    "Contact Support": "联系支持",
    "Try GitHub Copilot": "试试 GitHub Copilot",
    "Try GitHub Copilot for free": "免费试用 GitHub Copilot",
    "Search code": "搜索代码",
    "Search repositories": "搜索仓库",
    "Search users": "搜索用户",
    "Search topics": "搜索主题",
    "Search by language": "按语言搜索",
    "Sort by": "排序方式",
    "Best match": "最佳匹配",
    "Most stars": "最多星标",
    "Fewest stars": "最少星标",
    "Most forks": "最多复刻",
    "Fewest forks": "最少复刻",
    "Recently updated": "最近更新",
    "Least recently updated": "最早更新",
    "Most followers": "最多关注者",
    "Most recently joined": "最近加入",
    "Verified": "已验证",
    "Sponsor": "赞助",
    "Sponsor for": "赞助给",
    "Monthly": "每月",
    "One-time": "一次性",
    "Custom amount": "自定义金额",
    "Select a tier": "选择等级",
    "Select an amount": "选择金额",
    "No sponsors yet": "暂无赞助者",
    "No sponsorships yet": "暂无赞助",
    "Manage your sponsorship": "管理你的赞助",
    "Edit your sponsorship": "编辑你的赞助",
    "Cancel sponsorship": "取消赞助",
    "Tier": "等级",
    "Tiers": "等级",
    "Goal": "目标",
    "Goals": "目标",
    "Monthly goal": "月度目标",
    "Progress": "进度",
    "Raised": "已筹集",
    "Goal progress": "目标进度",
    "of": "/",
    "per month": "每月",
    "one time": "一次性",
    "Total sponsors": "总赞助者",
    "Total earnings": "总收入",
    "Net income": "净收入",
    "Payment method": "支付方式",
    "Payment history": "支付历史",
    "Payment pending": "支付待处理",
    "Payment processed": "支付已处理",
    "Payment failed": "支付失败",
    "Payment cancelled": "支付已取消",
    "Refund": "退款",
    "Invoice": "发票",
    "Receipt": "收据",
    "Billing date": "账单日期",
    "Next billing date": "下次账单日期",
    "Amount": "金额",
    "Description": "描述",
    "Transaction ID": "交易 ID",
    "Date": "日期",
    "Type": "类型",
    "Action": "操作",
    "User": "用户",
    "Users": "用户",
    "Admin": "管理员",
    "Owner": "所有者",
    "Collaborator": "协作者",
    "Guest": "访客",
    "Anonymous": "匿名",
    "Unknown": "未知",
    "None": "无",
    "N/A": "不适用",
    "Required": "必需",
    "Optional": "可选",
    "Recommended": "推荐",
    "Deprecated": "已弃用",
    "Experimental": "实验性",
    "Stable": "稳定",
    "Beta": "测试版",
    "Alpha": "内测版",
    "Early access": "抢先体验",
    "Coming soon": "即将推出",
    "Updated": "已更新",
    "Popular": "热门",
    "Featured": "精选",
    "Recommended for you": "为你推荐",
    "Based on your interests": "基于你的兴趣",
    "Based on repositories you've starred": "基于你星标的仓库",
    "Based on people you follow": "基于你关注的人",
    "Based on your network": "基于你的网络",
    "Suggested": "建议",
    "Suggestions": "建议",
    "Recently viewed": "最近查看",
    "Frequently used": "常用",
    "Quick actions": "快捷操作",
    "Keyboard shortcuts": "键盘快捷键",
    "Command palette": "命令面板",
    "Search for a command": "搜索命令",
    "Run a command": "运行命令",
    "Go to repository": "转到仓库",
    "Go to issue": "转到议题",
    "Go to pull request": "转到拉取请求",
    "Switch context": "切换上下文",
    "Switch account": "切换账户",
    "Switch organization": "切换组织",
    "Switch repository": "切换仓库",
    "Switch branch": "切换分支",
    "Switch to": "切换到",
    "Switch": "切换",
    "Toggle": "切换",
    "Enable": "启用",
    "Disable": "禁用",
    "On": "开",
    "Off": "关",
    "True": "真",
    "False": "假",
    "Enabled": "已启用",
    "Disabled": "已禁用",
    "Active": "活跃",
    "Inactive": "不活跃",
    "Pending": "待处理",
    "In progress": "进行中",
    "Completed": "已完成",
    "Failed": "失败",
    "Success": "成功",
    "Successful": "成功",
    "Error": "错误",
    "Warning": "警告",
    "Info": "信息",
    "Queued": "排队中",
    "Waiting": "等待中",
    "Running": "运行中",
    "Skipped": "已跳过",
    "Stale": "过期",
    "Timed out": "超时",
    "Cancelled": "已取消",
    "Aborted": "已中止",
    "Paused": "已暂停",
    "Resumed": "已恢复",
    "Retry": "重试",
    "Restart": "重新开始",
    "Rerun": "重新运行",
    "Rerun all jobs": "重新运行所有作业",
    "Rerun failed jobs": "重新运行失败的作业",
    "Download logs": "下载日志",
    "View logs": "查看日志",
    "View raw log": "查看原始日志",
    "View full log": "查看完整日志",
    "View summary": "查看摘要",
    "Annotations": "注释",
    "Artifacts": "产物",
    "Workflow": "工作流",
    "Workflows": "工作流",
    "Workflow runs": "工作流运行",
    "This workflow": "此工作流",
    "Run workflow": "运行工作流",
    "Disable workflow": "禁用工作流",
    "Enable workflow": "启用工作流",
    "Delete workflow": "删除工作流",
    "Pin workflow": "置顶工作流",
    "Unpin workflow": "取消置顶工作流",
    "Trigger": "触发器",
    "Triggers": "触发器",
    "Event": "事件",
    "Events": "事件",
    "Schedule": "计划",
    "Scheduled": "已计划",
    "Manual": "手动",
    "Workflow dispatch": "工作流调度",
    "Repository dispatch": "仓库调度",
    "Push": "推送",
    "Pull request": "拉取请求",
    "Issue": "议题",
    "Discussion": "讨论",
    "Deployment": "部署",
    "Deployment status": "部署状态",
    "Production": "生产",
    "Staging": "预发布",
    "Testing": "测试",
    "Review": "审核",
    "Reviews": "审核",
    "Changes requested": "请求更改",
    "Approved": "已批准",
    "Pending review": "待审核",
    "Review requested": "请求审核",
    "No review requested": "无审核请求",
    "Request review": "请求审核",
    "Request changes": "请求更改",
    "Approve": "批准",
    "Dismiss review": "驳回审核",
    "View review": "查看审核",
    "Show all review comments": "显示所有审核评论",
    "Resolve conversation": "解决对话",
    "Unresolve conversation": "取消解决对话",
    "Outdated": "已过时",
    "Resolved": "已解决",
    "Unresolved": "未解决",
    "Single comment": "单条评论",
    "Start a review": "开始审核",
    "Add review comments": "添加审核评论",
    "Add single comment": "添加单条评论",
    "Submit review": "提交审核",
    "Update review": "更新审核",
    "Delete pending review": "删除待审核",
    "View changes": "查看更改",
    "View diff": "查看差异",
    "View conversation": "查看对话",
    "View all conversations": "查看所有对话",
    "Show conversation": "显示对话",
    "Hide conversation": "隐藏对话",
    "Minimize": "最小化",
    "Maximize": "最大化",
    "Full screen": "全屏",
    "Exit full screen": "退出全屏",
    "Browse": "浏览",
    "Browse files": "浏览文件",
    "Browse repository": "浏览仓库",
    "Browse code": "浏览代码",
    "Browse issues": "浏览议题",
    "Browse pull requests": "浏览拉取请求",
    "Browse discussions": "浏览讨论",
    "Browse releases": "浏览发布",
    "Browse packages": "浏览包",
    "Browse marketplace": "浏览市场",
    "Browse topics": "浏览主题",
    "Browse collections": "浏览集合",
    "Browse sponsors": "浏览赞助者",
    "Browse trending": "浏览趋势",
    "Browse events": "浏览活动",
    "Browse guides": "浏览指南",
    "Browse docs": "浏览文档",
    "Browse API": "浏览 API",
    "Browse community": "浏览社区",
    "Browse forum": "浏览论坛",
    "Browse blog": "浏览博客",
    "Browse changelog": "浏览更新日志",
    "Browse feature previews": "浏览功能预览",
    "Browse settings": "浏览设置",
    "Browse profile": "浏览个人资料",
    "Browse organizations": "浏览组织",
    "Browse enterprises": "浏览企业",
    "Browse repositories": "浏览仓库",
    "Browse stars": "浏览星标",
    "Browse gists": "浏览代码片段",
    "Select all": "全选",
    "Deselect all": "取消全选",
    "Invert selection": "反选",
    "Select": "选择",
    "Deselect": "取消选择",
    "Selected": "已选择",
    "Unselected": "未选择",
    "Select an option": "选择一个选项",
    "Choose an option": "选择一个选项",
    "Choose": "选择",
    "Pick": "选取",
    "Clear filters": "清除筛选条件",
    "Clear search": "清除搜索",
    "Clear all": "全部清除",
    "No results found": "未找到结果",
    "Your search did not match any results": "你的搜索未匹配任何结果",
    "Try a different search term": "尝试不同的搜索词",
    "Try adjusting your filters": "尝试调整筛选条件",
    "results": "结果",
    "Showing": "显示",
    "Show results for": "显示结果",
    "Previous page": "上一页",
    "Next page": "下一页",
    "Page": "页"
  };

  function translateNode(node) {
    if (!node) return;
    if (node.nodeType === Node.TEXT_NODE) {
      var text = node.textContent.trim();
      if (text && T[text]) {
        node.textContent = node.textContent.replace(text, T[text]);
      }
    } else if (node.nodeType === Node.ELEMENT_NODE) {
      if (node.tagName === 'SCRIPT' || node.tagName === 'STYLE' || node.tagName === 'CODE' || node.tagName === 'PRE') return;
      if (node.tagName === 'INPUT' || node.tagName === 'TEXTAREA') return;
      translateAttributes(node);
      var children = node.childNodes;
      for (var i = 0; i < children.length; i++) {
        translateNode(children[i]);
      }
    }
  }

  function translateAttributes(el) {
    var attrs = ['placeholder', 'title', 'aria-label', 'data-hovercard-type'];
    for (var i = 0; i < attrs.length; i++) {
      var val = el.getAttribute(attrs[i]);
      if (val && T[val]) {
        el.setAttribute(attrs[i], T[val]);
      }
    }
    var tooltip = el.getAttribute('data-tooltip');
    if (tooltip && T[tooltip]) {
      el.setAttribute('data-tooltip', T[tooltip]);
    }
  }

  function translatePage() {
    try { translateNode(document.body); } catch (e) {}
  }

  translatePage();

  var observer = new MutationObserver(function(mutations) {
    for (var i = 0; i < mutations.length; i++) {
      var added = mutations[i].addedNodes;
      for (var j = 0; j < added.length; j++) {
        if (added[j].nodeType === Node.ELEMENT_NODE) {
          translateNode(added[j]);
        }
      }
    }
  });

  try {
    observer.observe(document.body, { childList: true, subtree: true });
  } catch (e) {}

  var url = location.href;
  setInterval(function() {
    if (location.href !== url) {
      url = location.href;
      setTimeout(translatePage, 500);
    }
  }, 1000);
})();
